# Generated by Django 5.1.3 on 2024-11-18 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(choices=[('Driver', 'Driver'), ('3 wood', '3 wood'), ('5 wood', '5 wood'), ('7 wood', '7 wood'), ('1i', '1i'), ('2i', '2i'), ('3i', '3i'), ('4i', '4i'), ('5i', '5i'), ('6i', '6i'), ('7i', '7i'), ('8i', '8i'), ('9i', '9i'), ('PW', 'PW'), ('50 degree', '50 degree'), ('52 degree', '52 degree'), ('54 degree', '54 degree'), ('56 degree', '56 degree'), ('58 degree', '58 degree'), ('60 degree', '60 degree')], max_length=20)),
                ('distance', models.PositiveIntegerField(help_text='Distance in yards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
